### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by 853103174** [linpeilie/mapstruct-plus#31]
用IDE启动多模块项目 每次修改配置注解的类以后 重新启动项目报错 重新用Maven clean compile以后就没有问题了

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.jiajiayue.txjm.shop.order.OrderApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'prodToProdCategoryVOMapperImpl' for bean class [com.jiajiayue.txjm.shop.order.common.model.ProdToProdCategoryVOMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [com.jiajiayue.txjm.shop.order.common.converter.ProdToProdCategoryVOMapperImpl]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.jiajiayue.txjm.shop.order.OrderApplication.main(OrderApplication.java:36)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'prodToProdCategoryVOMapperImpl' for bean class [com.jiajiayue.txjm.shop.order.common.model.ProdToProdCategoryVOMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [com.jiajiayue.txjm.shop.order.common.converter.ProdToProdCategoryVOMapperImpl]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
	... 13 common frames omitted

**Comment by linpeilie** [comment]
这个本地没有复现，方便的话，可以提供一个测试的复现项目

**Comment by 853103174** [comment]
好像是我本地设置的问题 用了Save Actions插件
同时勾选了 [experimental] Compile files (using "Build > Build Project")

**Comment by linpeilie** [comment]
好，我也试一下

**Comment by linpeilie** [comment]
找到原因了，IDEA是部分编译，所以部分编译的时候，配置类没有生效，我把mapperPackage这个属性去掉吧，马上发个版本🤦‍♂️
