### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by aeroyu** [linpeilie/mapstruct-plus#48]
Internal error in the mapping processor: java.util.ServiceConfigurationError: org.mapstruct.ap.internal.processor.ModelElementProcessor: Provider org.mapstruct.ap.internal.processor.JakartaCdiComponentProcessor not found  	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)  	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)  	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)  	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)  	at org.mapstruct.ap.MappingProcessor.getProcessors(MappingProcessor.java:359)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:316)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:237)  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:524)  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:587)  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:522)  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:366)  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:291)  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:245)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1523)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1153)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1303)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1118)  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:889)  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:471)  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:150)  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:371)  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:193)  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:211)  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)  	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by linpeilie** [comment]
什么环境，用的 jakarta-cdi 注入？

**Comment by linpeilie** [comment]
方便的话，可以建一个测试项目，我看下
