### ISSUE TITLE
cannot find converter from OptTableVo to TableInfos

### ISSUE THREAD

**Issue by zhongzai01** [linpeilie/mapstruct-plus#98]
异常堆栈：
```java
io.github.linpeilie.ConvertException: cannot find converter from OptTableVo to TableInfos
	at io.github.linpeilie.Converter.convert(Converter.java:31)
	at com.lantin.common.core.utils.MapstructUtils.convert(MapstructUtils.java:38)
	at com.lantin.data.service.impl.TableService.optTable(TableService.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
	at com.lantin.data.service.impl.TableService$$SpringCGLIB$$0.optTable(<generated>)
	at com.lantin.data.controller.admin.TableController.optTable(TableController.java:63)
```

相关依赖：
 ```xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.lantin</groupId>
    <artifactId>lantin-back-main</artifactId>
    <version>${revision}</version>

    <name>lantin-back-main</name>
    <packaging>pom</packaging>
    <description>兰亭Ai平台</description>

    <properties>
        <revision>1.0</revision>

        <!-- annotationProcessor-->
        <lombok.version>1.18.32</lombok.version>
        <mapstruct-plus.version>1.4.3</mapstruct-plus.version>
        <mapstruct-plus.lombok.version>0.2.0</mapstruct-plus.lombok.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
    </properties>

  
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <!-- 关闭过滤 -->
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <!-- 引入所有 匹配文件进行过滤 -->
                <includes>
                    <include>application*</include>
                    <include>bootstrap*</include>
                    <include>banner*</include>
                </includes>
                <!-- 启用过滤 即该资源中的变量将会被过滤器中的值替换 -->
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <!--  compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.verison}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.linpeilie</groupId>
                            <artifactId>mapstruct-plus-processor</artifactId>
                            <version>${mapstruct-plus.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${mapstruct-plus.lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
    </build>

</project>
```

相关target包生成：
<img width="1600" alt="image" src="https://github.com/user-attachments/assets/e2594b69-8baa-44c9-a086-9e6886154506">

经测试 降级为以前版本 （1.3.6） 使用正常：
1.3.6相关target包生成
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/ae2d5548-4638-4545-8d35-46497e6f6a95">

**Comment by linpeilie** [comment]
最新版本没有生成么，target目录下，com包下是什么

**Comment by zhongzai01** [comment]
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/eb87ebd0-4da4-4aba-937f-0414269e3b38">

**Comment by zhongzai01** [comment]
编译并没有 报错，clean后重新编译这是常识，已实验多次

**Comment by linpeilie** [comment]
还是第一次遇到这个问题，没有办法复现，方便的话，可以加下我联系方式，我远程看一下。
